thaiinter_api/qrcodes/urls.py
from django.urls import path
from . import views

app_name = 'qrcodes'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_roof, name='add_roof'),
    path('add/roof_color/', views.add_roof_color, name='add_roof_color'),
    path('add/roof_type/', views.add_roof_type, name='add_roof_type'),
    path('add/roof_size/', views.add_roof_size, name='add_roof_size'),
    path('<int:roof_id>/', views.roof_detail, name='roof_detail'),
    path('<uuid:qr_code_id>/', views.qr_code_detail, name='qr_code_detail'),
    path('print/<str:qr_code_id>/', views.print_qr_code, name='print_qr_code'),
    path('download_and_redirect/<str:qr_code_id>/', views.download_and_redirect, name='download_and_redirect'),
]

thaiinter_api/thaiinter_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import CustomLoginView, CustomLogoutView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('items/', include('qrcodes.urls')),
    path('tracking/', include('tracking.urls')),
    # path('auth/', include('authentication.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

thaiinter_api/tracking/urls.py
from django.urls import path
from . import views

app_name = 'tracking'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:qr_code_id>/', views.track_roof, name='track_roof'),
    path('<str:qr_code_id>/add_process_name/', views.add_process_name, name='add_process_name'),
]

thaiinter_api/templates/base.html
<!-- in templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}ระบบติดตามสินค้าด้วย QR code{% endblock %}</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background-color: #1e1f21;
      color: #fff;
    }

    header {
      background-color: #0074d9;
      padding: 20px;
    }

    h1 {
      margin: 0;
      font-size: 36px;
      font-weight: normal;
    }

    nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-top: 20px;
    }

    nav ul {
      list-style: none;
      margin: 0;
      padding: 0;
      display: flex;
    }

    nav li {
      margin-right: 20px;
    }

    nav a {
      color: #fff;
      text-decoration: none;
      font-size: 18px;
    }

    nav a:hover {
      text-decoration: underline;
    }

    main {
      padding: 20px;
    }

    footer {
      background-color: #000;
      color: #fff;
      padding: 20px;
      text-align: center;
    }

    footer p {
      margin: 0;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <header>
    <h1>{% block heading %}ระบบติดตามสินค้าด้วย QR code{% endblock %}</h1>
    <nav>
      <ul>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
      </ul>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
      </form>
    </nav>
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
    <p>&copy; 2023 ระบบติดตามสินค้าด้วย QR code</p>
  </footer>
</body>
</html>

thaiinter_api/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Contact</title>
  </head>
  <body>
    <h1>มีปัญหาติดต่อ</h1>
    <p>icenuttun@gmail.com</p>
  </body>
</html>
{% endblock %}

thaiinter_api/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <h1>Welcome to my app!</h1>
{% endblock %}

thaiinter_api/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    <h1>Welcome to my website!</h1>
    <p>Here are some links to my apps:</p>
    <ul>
      <li><a href="{% url 'qrcodes:index' %}">QR Codes App</a></li>
      <li><a href="{% url 'tracking:index' %}">Tracking App</a></li>
    </ul>
  </body>
</html>
{% endblock %}